### ISSUE TITLE
作者是不是没有封装把已选的传入的功能

### ISSUE THREAD

**Issue by hinzcn** [donkingliang/ImageSelector#10]
我看 demo 里面有ImageSelectorUtils.openPhoto(DemoActivity.this, REQUEST_CODE, false, 0, mAdapter.getImages()); 这行代码，但是ImageSelectorUtils 类并没有对于的方法

**Comment by donkingliang** [comment]
有这个方法啊，你看一下源码。1.4.0版本就已经加了。

**Comment by hinzcn** [comment]
看到了，我用了老版本，擦。不说了，star走起
