### ISSUE TITLE
关于APP内新拍摄的图片保存到本地，ImageSelector显示不出来的问题

### ISSUE THREAD

**Issue by hinzcn** [donkingliang/ImageSelector#11]
大神，有什么解决办法吗

**Comment by donkingliang** [comment]
第三方应用调起系统相机拍照，拍摄的照片一般是不会保存到手机相册的，如果你想保存图片，你只能是自己拿到图片，然后保存到某个目录下。
如果你已经自己把图片保存了，ImageSelector没有显示，可能是因为你把图片保存到了APP的私有文件夹，所以ImageSelector没有扫描到。也可能是你保存的图片没有后缀名，所以ImageSelector没有识别到。
