### ISSUE TITLE
关于图片的展示

### ISSUE THREAD

**Issue by qiahaungzhang** [donkingliang/ImageSelector#12]
你好，我使用了你的工具类在mainActivity中使用，可总是执行不到onActivityResult中，图片也没有办法显示，你看是什么问题。

**Comment by donkingliang** [comment]
你好，你是说onActivityResult这个方法没有回调到吗？你的REQUEST_CODE是多少？不能小于0哦。

**Comment by qiahaungzhang** [comment]
可以使用了。请问能用在fragment中吗？我实验了一下，图片就显示不了。

**Comment by donkingliang** [comment]
可以在Fragment中使用的。参考这个：[https://github.com/donkingliang/ImageSelector/issues/3](url)
