### ISSUE TITLE
可不可以加个进入相册点击图片不大图预览，直接为选中的入口参数

### ISSUE THREAD

**Issue by MJJSai** [donkingliang/ImageSelector#15]

**Comment by donkingliang** [comment]
我现在设计是点击图片预览，点击图片的右上角直接选中。
你是想不要预览，点击就直接选中吗？如果是这样，就没有图片预览的功能咯。

**Comment by donkingliang** [comment]
1.6.5版本添加了这个配置的功能。
setViewImage(false) //是否点击放大图片查看,，默认为true

**Comment by MJJSai** [comment]
Bravo!
