### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by MoShengLinQi** [donkingliang/ImageSelector#16]
![image](https://user-images.githubusercontent.com/19679816/40648271-97602a4e-6360-11e8-8f7c-21f314b4c787.png)

**Comment by donkingliang** [comment]
错误显示是找不到activity_image_select.xml这个布局文件，但是我的库里是已经把这个文件打包进去了。你看一下你引用的库有没有这个文件，或者是不是你的项目中也有另外一个这样命名的文件而引起资源冲突。
