### ISSUE TITLE
一些建議

### ISSUE THREAD

**Issue by Gitgitgitgghub** [donkingliang/ImageSelector#19]
1.設定為單選模式時 圖片上的圈圈可以消除掉，畢竟點了就進入預覽了..

2.希望可以選擇圖片後，可以選擇 直接按確定取得圖片，也就是說不點選預覽的情況下不進入預覽

謝謝作者開發這麼好用的庫，方便大家。感恩再感恩

**Comment by donkingliang** [comment]
好的，多谢建议。因为我当初做这个选择器的时候，是参考微信的图片选择器做的，所以交互也是跟微信的一样。你的建议我会考虑要不要在后续的版本做优化。多谢。
