### ISSUE TITLE
ImageModel 里面导致OOM

### ISSUE THREAD

**Issue by xqx0415** [donkingliang/ImageSelector#2]
ImageModel 里面获取完本地图片后，没有关闭游标，多试几次就OOM了

**Comment by donkingliang** [comment]
大意了。多谢提示，我得赶紧去改。

**Comment by donkingliang** [comment]
你好，我检查了一下代码。游标有关闭啊。
`if(!mCursor.moveToNext()) {
         mCursor.close();
         break;
      }`
你的问题是不是其他原因引起的。如果你找到问题所在，请回复一下，我好改进，谢谢！

**Comment by xqx0415** [comment]
我引用的那一版我看源码是没有关闭的，然后我看你的最新代码是有关闭的，会不会是没有把最新的更新到仓库里面？

**Comment by xqx0415** [comment]
好的
