### ISSUE TITLE
选择圆形图标太小

### ISSUE THREAD

**Issue by erchuanliu** [donkingliang/ImageSelector#21]
最近在使用功能的时候发现选择的按钮有点小，点击选择不太方便，能不能把选择按钮放大一些。还有发现一个问题，单张选择的时候会报错。

**Comment by donkingliang** [comment]
你好。按钮小的问题，我可以把按钮的可点击范围放大一点。至于单选报错，是报什么错啊，能把你遇到的错误信息和操作发出来吗。因为我测试时并没有发生错误。

**Comment by donkingliang** [comment]
按钮和复选框可以考虑作成配置的。这样图片大小的配置，我觉得这个需求不具有通用性，如果你需要这样的需求，建议你下载源码修改。
