### ISSUE TITLE
选择图片界面，有些图片显示全黑，也无法预览

### ISSUE THREAD

**Issue by liu-yongliao** [donkingliang/ImageSelector#24]
你好，在选择图片界面中，加载出的图片有部分是全黑的， 预览也是黑色，无法查看原图，点击确定返回的图片也是全黑的。

**Comment by donkingliang** [comment]
你好，你用的是最新版的吗？你这种情况一般是因为图片文件未下载完成或者图片文件损害引起的。我在1.5.1版本过滤了未下载完成的图片，但是损坏的图片就没有办法在搜索图片的时候过滤了。

建议你看一下微信的图片选择器是否也是这样，我估计是图片损坏的问题。

**Comment by liu-yongliao** [comment]
你好，我的版本是1.6.5，在微信的图片选择器上 能看到这里显示黑色的图片，是可以正常显示的；
