### ISSUE TITLE
开启选择页面的上下文不只有activity还有可能是fragment，能支持下吗？

### ISSUE THREAD

**Issue by bluesatan0-0** [donkingliang/ImageSelector#26]
ImageSelector.builder()
                       .useCamera(true)
                       .setSingle(true)
                       .setViewImage(true)
                       .setSelected(imgs)
                       .start(getActivity(), REQUEST_CODE);
从Fragment中使用这段代码，用的却是activity的startActivityForResult，结果也返回给了父activity而不是发起调用的fragment页面。
可以重载一个start(Fragment frag，int requestCode)方法吗？相应的用frag.startActivityForResult()能更准确地接收结果。

**Comment by donkingliang** [comment]
好的，多谢反馈！你的建议我会在后面的版本加上，谢谢！
