### ISSUE TITLE
你这个工具不适用于fragment

### ISSUE THREAD

**Issue by guofucheng** [donkingliang/ImageSelector#3]
你可以自己试试，在Fragment里面是无法回调onActivityResult的，因为fragment回调onActivityResult只能直接使用startActivityforResult，参数那里只能传入getActivity

**Comment by donkingliang** [comment]
是的，我在ImageSelectorUtils工具类和例子中只提供了用activity启动选择器和接收数据的方法。这也是我建议用的方法。你可以在activity接收数据后自己分发到目标fragment。

**Comment by donkingliang** [comment]
其实用fragment启动和接收数据也是可以的。你不调用ImageSelectorUtils里的方法，自己在fragment启动选择器。比如：
`Intent intent = new Intent(mContext, ImageSelectorActivity.class);
                intent.putExtra(Constants.MAX_SELECT_COUNT, maxSelectCount);
                intent.putExtra(Constants.IS_SINGLE, isSingle);
                startActivityForResult(intent, requestCode);`
然后你就可以在fragment的onActivityResult方法中接收数据了。

**Comment by tyr285687545** [comment]
//预加载
                        ImageSelector.preload(requireContext())

                        val intent = Intent(
                            requireContext(),
                            ImageSelectorActivity::class.java
                        )

                        intent.putExtra(KEY_CONFIG, RequestConfig().apply {
                            isSingle = true
                            maxSelectCount = 1
                        })
