### ISSUE TITLE
在小米上选择图片会旋转90度！

### ISSUE THREAD

**Issue by cozing** [donkingliang/ImageSelector#30]
奇怪

**Comment by donkingliang** [comment]
因为选择器只是返回图片的路径。而系统存储的图片可能是有旋转角度的，所以我们在显示手机或拍照的图片时，需要处理图片的旋转角度问题。一般的图片加载框架（如：Glide）都会在框架里处理这个问题，所以我们很少自己去关注它。
[https://blog.csdn.net/joe_storm/article/details/51143839](https://blog.csdn.net/joe_storm/article/details/51143839)
