### ISSUE TITLE
使用1.6.7 发现拍照之后的照片 使用多图片使用问题

### ISSUE THREAD

**Issue by hy5201314** [donkingliang/ImageSelector#31]
在使用1.6.7 拍照之后 在使用图片选择器的时候 由于扫描图片 并没有扫描到Pictures 文件夹下的图片 导致 选择图片 还是可以选择最大图片  也就是说 最大选择三张图片 ， 拍照一张图片  然后在图片选择中 并不显示 还可以选择三张。

**Comment by donkingliang** [comment]
并不是选择器没有扫描Pictures文件夹的图片，而是Android第三方应用调起系统相机拍出来的照片，不会出现在相册里，所以扫描不出来的。这个问题我在以后的版本会尝试解决。多谢你反馈。
