### ISSUE TITLE
目录和相片数量多了会导致加载不出来

### ISSUE THREAD

**Issue by tianfeng94666** [donkingliang/ImageSelector#37]
我这边有7000多个目录每个目录一个照片，测试了多个仿微信图片选择器，发现都hold不住，但是微信自带的ok

**Comment by joker-fu** [comment]
这个测试环境还有么

**Comment by JustinChiang123** [comment]
能加载出来 非常慢，现在手机动不动就是100 200G的  海量照片 gif 什么的，加载非常慢。建议作者把缓存做进去。

**Comment by onlyay** [comment]
我的也是本地照片加载非常卡
