### ISSUE TITLE
关于图片预览BUG

### ISSUE THREAD

**Issue by Leeko-Lau** [donkingliang/ImageSelector#40]
与调起图片选择器中的预览按钮无关
描述：在图片选择器选择完图片后进行了列表展示，然后想做个点击图片进行预览的效果，猛然发现源码里有PreviewActivity类，因此直接使用PreviewActivity.openActivity()方法打开预览界面，预览正常。但是当点击选择按钮时（相当于取消选择该照片），PagerAdapter异常，下面是完整错误：The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 6, found: 5 Pager id: com.example.admin.imageutil:id/vp_image Pager class: class com.donkingliang.imageselector.view.MyViewPager Problematic adapter: class com.donkingliang.imageselector.adapter.ImagePagerAdapter

**Comment by donkingliang** [comment]
PreviewActivity是框架里的预览页面，它跟选择器里的图片列表页面在业务逻辑上有关联。并不是可以独立的使用的页面，所以理论上应该是不能给外面直接打开使用。

**Comment by Leeko-Lau** [comment]
嗯嗯，那只能自己做一个预览页面了，其实如果可以的话可以把预览界面做成能提供外面使用也不错的，只是个小小的建议
