### ISSUE TITLE
在android10.0系统的手机中图片选择界面所有图片都是黑色的，调用相机拍照完成后，一直显示正在处理

### ISSUE THREAD

**Issue by yfm372886980** [donkingliang/ImageSelector#42]

**Comment by donkingliang** [comment]
你好，你是否测试过是什么原因造成的问题。我这个没有android 10的测试机器。我用其他版本的机器测试没有发现这个问题，不知道是什么原因造成的问题。

**Comment by yfm372886980** [comment]
谢谢你能关注到我的问题，这个问题是android10.0才出现的问题。我是在oppo开放平台远程真机测试发现的（https://open.oppomobile.com/cloudmachine/device/list）。现在各厂商都快要发布android10.0的系统和手机，很多兼容性问题，正紧急通知应用市场上的app做兼容性适配，如果这个问题得以修复烦请通知我哦。




------------------ 原始邮件 ------------------
发件人: "donkingliang"<notifications@github.com>;
发送时间: 2019年8月26日(星期一) 中午11:32
收件人: "donkingliang/ImageSelector"<ImageSelector@noreply.github.com>;
抄送: "姚凤鸣"<372886980@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [donkingliang/ImageSelector] 在android10.0系统的手机中图片选择界面所有图片都是黑色的，调用相机拍照完成后，一直显示正在处理 (#42)




你好，你是否测试过是什么原因造成的问题。我这个没有android 10的测试机器。我用其他版本的机器测试没有发现这个问题，不知道是什么原因造成的问题。

**Comment by yizems** [comment]
Android 10 的确存在该问题,因为文件权限变更了,所以需要该库适配android 10
