### ISSUE TITLE
ImageAdapter.getFirstVisibleImage()下标越界

### ISSUE THREAD

**Issue by easytobreakdown** [donkingliang/ImageSelector#46]
com.donkingliang.imageselector.adapter.ImageAdapter.getFirstVisibleImage()
    mImages.get(firstVisibleItem == 0 ? 0 : firstVisibleItem - 1);
firstVisibleItem小于0就报错了,过滤firstVisibleItem扩大些范围吧.
建议改为:mImages.get(firstVisibleItem <= 0 ? 0 : firstVisibleItem - 1);

**Comment by donkingliang** [comment]
多谢反馈。firstVisibleItem确实有可能为-1，我忽略了。这个bug我会在后面的版本修复。谢谢！
