### ISSUE TITLE
单独使用图片预览的问题

### ISSUE THREAD

**Issue by a844672236** [donkingliang/ImageSelector#47]
单独使用PreviewActivity页面,传递数据之后无法拿到更改过后(点击右下取消选择后)的数据,而且更改过后会抛异常(由vp数据源更改引起)

**Comment by donkingliang** [comment]
你直接打开PreviewActivity吗？PreviewActivity只提供选择器内部预览，不提供给外部使用的。

**Comment by a844672236** [comment]
我是跟着ImageSelectorAc内部的逻辑去写的,就是没太看懂两者之间数据变化是怎么做到的...

方便加QQ交流下不?
