### ISSUE TITLE
所有图片中有重复图片

### ISSUE THREAD

**Issue by 214024475** [donkingliang/ImageSelector#5]
打开所有图片发现很多图片都是重复的，而且相机拍照照片没有扫描出来

**Comment by donkingliang** [comment]
图片重复的问题，你看一下是不是你的手机了本来就有多张一样的图片。因为路径相同的图片应该不会重复扫描出来的。你可以看一下手机自带的相册或者是微信的相册是否也有这样的情况。
相机拍照照片没有扫描出来可能是因为有一些手机是不保存第三方因为调起相机所拍的图片的。也有可能是因为相机保存图片的位置是私有的，或者在内置内存卡的，不过这种情况在很老的手机有，现在的手机一般都不会有这样的问题了。
