### ISSUE TITLE
从相册进行拍照后出现两张照片

### ISSUE THREAD

**Issue by lfc1101** [donkingliang/ImageSelector#56]
选择相册图片时，调用拍照功能，拍完后会出现两张照片

**Comment by donkingliang** [comment]
是特定手机会这样吗？一般由第三方应用调起相机拍照，图片是不会保存到系统图库的，所以我自己把拍照图片插入图库。可能是某些手机也会把第三方应用调起的拍照图片插入图库，所以导致重复了。

**Comment by lfc1101** [comment]
> 是特定的手机会这样吗？？一般由第三方应用调起相机拍照，图片是不会保存到系统图库的，所以我自己把照片图片插入图库。可能是某些手机也会把第三方应用调起的拍摄图片插入图库，因此导致重复了

不是特定手机，模拟器，金立，华为，小米我用了好多个手机都会出现这种情况，请问该怎么解决呢，记得之前没有问题的，是最近才出现这个问题的。我也没有修改过代码。

**Comment by donkingliang** [comment]
你使用的是哪个版本的代码。你的手机时什么版本的？我用华为的android 10手机，也没有出现你说的问题。

**Comment by donkingliang** [comment]
你下载一下我的代码，注释下面这两句代码试一下。
![image](https://user-images.githubusercontent.com/5499532/81136655-d16e0d80-8f8e-11ea-98a3-484c5abb8137.png)

**Comment by lfc1101** [comment]
我的是金立8.1.0，，，，华为是10，，好的我注释一下试试

**Comment by lfc1101** [comment]
我刚用金立8.1测试过不注释代码的情况下会保存两张图片，注释完代码，就是正常的一张，然后用了一个1+9.0手机测试，不注释代码也是正常的一张图片。

**Comment by lfc1101** [comment]
是因为手机的原因嘛？还是版本的原因？

**Comment by donkingliang** [comment]
应该是我上面说的那样，有些手机会默认把第三方拍照的图片也插入系统图片，所以就导致重复了。但是目前没有好的办法判断系统会不会默认把图片插入，所以现在要么就是我们不插入。

**Comment by donkingliang** [comment]
注释的两句代码，就是我们插入图片的代码。去掉后，大部分手机就可能不会显示我们自己拍照的图片了

**Comment by lfc1101** [comment]
嗯嗯，目前只能先这样了，谢谢啦
