### ISSUE TITLE
多次选择，不保存之前选择的记录

### ISSUE THREAD

**Issue by weitto** [donkingliang/ImageSelector#6]
例如，第一次选2张，返回出去。刚好想起来还要再添加2张，再去选择，会出现这样的问题。

**Comment by donkingliang** [comment]
是不保存的。因为每次都是重新打开相册的，所以在打开相册的时候，选择器并不知道你以前有没有选择过图片。

**Comment by donkingliang** [comment]
新版本可以在再次打开选择器时，传入已选过的图片，使这些图片默认为选中状态。
