### ISSUE TITLE
不能取消预览

### ISSUE THREAD

**Issue by wsfbailebai** [donkingliang/ImageSelector#65]
ImageSelector.builder()
                        .useCamera(false) // 设置是否使用拍照
                        .setSingle(true)  //设置是否单选
                        .canPreview(false) //是否可以预览图片，默认为true
                        .start(this, REQUEST_CODE_CHOOSE); // 打开相册
选择图片时，页面右下角还是有预览按钮。

**Comment by donkingliang** [comment]
是否可以预览图片的属性只限制是否可以点击图片预览，不限制页面右下角的预览按钮。

**Comment by wsfbailebai** [comment]
明白了
