### ISSUE TITLE
点击列表预览图片，删除列表中图片如何实现呢

### ISSUE THREAD

**Issue by yaoxin521123** [donkingliang/ImageSelector#66]
点击列表预览图片，删除列表中图片如何实现呢

**Comment by donkingliang** [comment]
图片选择器里不能删除图片，只能选中和取消选中。如果你想从手机删除一张图片，只能到手机的相册删除。

**Comment by yaoxin521123** [comment]
能不能做个类似与微信发朋友圈那种，imageadapter里 做个点击列表图片的预览和删除，直接作用adapter里的数据，这样的功能。

**Comment by donkingliang** [comment]
图片选择器实现的是图片选择的功能，比如发朋友圈时，从相册选择图片的这一步功能。如果在选择器中做图片删除的操作，就会把手机里的图片删除掉的。

你想实现朋友圈发布页的功能，其实也很简单，你从图片选择器中获取到选择的图片，使用RecyclerView列表显示，点击预览就跳到新的页面，把图片带过去显示。点击删除，就从列表数据中移除图片，刷新列表就可以了。

这种功能是业务相关的，不是基础功能，所以我不会库里提供这样的功能。

**Comment by yaoxin521123** [comment]
好的，谢谢！
