### ISSUE TITLE
 java.lang.IllegalArgumentException: Invalid token limit

### ISSUE THREAD

**Issue by moz1q1** [donkingliang/ImageSelector#69]
java.lang.IllegalArgumentException: Invalid token limit

**Comment by moz1q1** [comment]
04-26 10:20:48.093 21559 23470 E AndroidRuntime: java.lang.IllegalArgumentException: Invalid token limit
04-26 10:20:48.093 21559 23470 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
04-26 10:20:48.093 21559 23470 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
04-26 10:20:48.093 21559 23470 E AndroidRuntime: 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
04-26 10:20:48.093 21559 23470 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1197)
04-26 10:20:48.093 21559 23470 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1128)
04-26 10:20:48.093 21559 23470 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1084)
04-26 10:20:48.093 21559 23470 E AndroidRuntime: 	at com.donkingliang.imageselector.utils.ImageUtil.isNeedSavePicture(ImageUtil.java:338)
04-26 10:20:48.093 21559 23470 E AndroidRuntime: 	at com.donkingliang.imageselector.utils.ImageUtil.access$000(ImageUtil.java:24)
04-26 10:20:48.093 21559 23470 E AndroidRuntime: 	at com.donkingliang.imageselector.utils.ImageUtil$1.run(ImageUtil.java:321)
04-26 10:20:48.093 21559 23470 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)

**Comment by donkingliang** [comment]
你好，这个bug我之前有修复过。但是因为这个bug只在一些特定手机出现，我没有可以验证这个bug的测试机，所以我没有更新版本。

麻烦你拉一下我github上的代码，帮我测试一下是否已经修复。谢谢！

**Comment by moz1q1** [comment]
这是安卓11必现的

**Comment by moz1q1** [comment]
麻烦你拉一下我github上的代码 你说你demo代码吗

**Comment by donkingliang** [comment]
> 麻烦你拉一下我github上的代码 你说你demo代码吗

是的

**Comment by moz1q1** [comment]
你依赖库能升级吗

**Comment by donkingliang** [comment]
> 你依赖库能升级吗

我现在还没有发新版。你把我测试一下，如果没有问题，我明天就发个新版。

现在我适配android 11是用模拟器测试的，我不确定真机上的效果，所以没有发版。

**Comment by Jxlimeng** [comment]
在Android R上面不建议使用sql语句的形式查询，使用sql语句的形式查询就会抛异常
下面文档解释了为什么会抛异常
[https://blog.csdn.net/u010471406/article/details/118112086](url)

**Comment by cbuemc** [comment]
> 在Android R上面不建议使用sql语句的形式查询，使用sql语句的形式查询就会抛异常
> 下面文档解释了为什么会抛异常
> [https://blog.csdn.net/u010471406/article/details/118112086](url)

请问有什么修复的办法？

**Comment by Jxlimeng** [comment]
> > 在Android R上面不建议使用sql语句的形式查询，使用sql语句的形式查询就会抛异常
> > 下面文档解释了为什么会抛异常
> > [https://blog.csdn.net/u010471406/article/details/118112086](url)
> 
> 请问有什么修复的办法？

 Bundle queryArgs = new Bundle();
 queryArgs.putInt(ContentResolver.QUERY_ARG_OFFSET, 0);
 queryArgs.putInt(ContentResolver.QUERY_ARG_LIMIT, 1);

具体原因可以看上面提供的文档
