### ISSUE TITLE
加不进去依赖.....

### ISSUE THREAD

**Issue by xxzgithub** [donkingliang/ImageSelector#7]
/media/F/Android/Release/app/build.gradle
    Error:Error:line (29)Failed to resolve: com.github.donkingliang:ImageSelector:1.3.1
<a href="openFile:/media/F/Android/Release/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

Android 版本是
26

**Comment by donkingliang** [comment]
有没有添加
repositories {
	...
	maven { url 'https://jitpack.io' }
	}
看使用的介绍。
