### ISSUE TITLE
搞进了demo里才发现没有相机模块

### ISSUE THREAD

**Issue by yueyingsk** [donkingliang/ImageSelector#8]
要是能把微信模块加到第一个格子里让选择是否拍照选取照片就完美了

**Comment by donkingliang** [comment]
是的，现在是没有拍照功能的。我在项目开发中，图片选择和拍照都是分开封装的。

**Comment by yueyingsk** [comment]
@donkingliang 其实还是封装里面好的，在外面不用先选择一次了，比较方便而且看起来更统一，我在我们的项目中就是直接放在里面了lol
