### ISSUE TITLE
权限获取问题

### ISSUE THREAD

**Issue by YanYangTan** [donkingliang/ImageSelector#80]
我使用的是OnePlus 9R测试，调用时一直要求相册和存储权限，但是事实上我已经把所有权限都开完了。
我试了其它Android设备都没问题，唯独这个不行。我感觉时OS不适配的问题，项目内的权限和OS 的权限或许有区别，能不能开一个接口，就是不强制要求权限，如果没权限，调用提示一次就行，然后继续执行，不要强制

**Comment by YanYangTan** [comment]
估计是这个PERMISSION_WRITE_EXTERNAL_REQUEST_CODE权限问题，因为11以上好象就不支持了

**Comment by shouPol** [comment]
请问一下怎么处理的，我也遇到了这个问题，在Android 14设备上出现的

**Comment by YanYangTan** [comment]
> 请问一下怎么处理的，我也遇到了这个问题，在Android 14设备上出现的

我直接换库了

**Comment by shouPol** [comment]
谢谢你，祝你天天开心

**Comment by shouPol** [comment]
> > 请问一下怎么处理的，我也遇到了这个问题，在Android 14设备上出现的
> 
> 我直接换库了

其他库可以吗？我还以为是Android14的问题。。。麻烦推荐一下

**Comment by YanYangTan** [comment]
我是用的这个 https://github.com/LuckSiege/PictureSelector
